// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"errors"
	"github.com/deantook/topi-api/internal/config"
	"github.com/deantook/topi-api/internal/handler"
	"github.com/deantook/topi-api/internal/mcp/handlers"
	"github.com/deantook/topi-api/internal/mcpsetup"
	"github.com/deantook/topi-api/internal/middleware"
	"github.com/deantook/topi-api/internal/repository"
	"github.com/deantook/topi-api/internal/service"
	"github.com/deantook/topi-api/pkg/jwt"
	"github.com/gin-gonic/gin"
	"github.com/swaggo/files"
	"github.com/swaggo/gin-swagger"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeServer() (*Server, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := provideDB(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	helper, err := provideJWT(configConfig)
	if err != nil {
		return nil, err
	}
	authService := service.NewAuthService(userRepository, helper)
	authHandler := handler.NewAuthHandler(authService)
	taskRepository := repository.NewTaskRepository(db)
	taskService := service.NewTaskService(taskRepository)
	listRepository := repository.NewListRepository(db)
	listService := service.NewListService(listRepository)
	dashboardHandler := handler.NewDashboardHandler(taskService, listService)
	listHandler := handler.NewListHandler(listService)
	taskHandler := handler.NewTaskHandler(taskService)
	mcpTokenService := service.NewMcpTokenService(userRepository)
	mcpTokenHandler := handler.NewMcpTokenHandler(mcpTokenService)
	taskHandlers := handlers.NewTaskHandlers(taskService)
	listHandlers := handlers.NewListHandlers(listService)
	mcpServer := mcpsetup.NewMCPServer(configConfig, taskHandlers, listHandlers, helper)
	engine := provideRouter(configConfig, authHandler, dashboardHandler, listHandler, taskHandler, mcpTokenHandler, mcpServer, helper)
	server := &Server{
		Engine: engine,
		Config: configConfig,
		DB:     db,
	}
	return server, nil
}

// wire.go:

type Server struct {
	Engine *gin.Engine
	Config *config.Config
	DB     *gorm.DB
}

func provideDB(cfg *config.Config) (*gorm.DB, error) {
	return gorm.Open(mysql.Open(cfg.DSN), &gorm.Config{})
}

func provideJWT(cfg *config.Config) (*jwt.Helper, error) {
	if cfg.JWTSecret == "" {
		return nil, errors.New("JWT_SECRET is required")
	}
	return jwt.NewHelper(cfg.JWTSecret, cfg.JWTExpireHours), nil
}

func provideRouter(
	cfg *config.Config,
	authH *handler.AuthHandler,
	dashboardH *handler.DashboardHandler,
	listH *handler.ListHandler,
	taskH *handler.TaskHandler,
	mcpTokenH *handler.McpTokenHandler,
	mcpServer *mcpsetup.MCPServer,
	jwtHelper *jwt.Helper,
) *gin.Engine {
	gin.SetMode(cfg.GinMode)
	r := gin.New()
	r.Use(gin.Recovery())
	r.Use(middleware.CORS(cfg.CORSOrigin))

	v1 := r.Group("/api/v1")
	{
		v1.POST("/register", authH.Register)
		v1.POST("/login", authH.Login)

		auth := v1.Group("")
		auth.Use(middleware.Auth(jwtHelper))
		auth.Use(middleware.Timezone())
		{
			auth.GET("/dashboard", dashboardH.Dashboard)
			auth.GET("/tasks", taskH.List)
			auth.POST("/tasks", taskH.Create)

			auth.POST("/tasks/batch", taskH.CreateBatch)
			auth.POST("/tasks/reorder", taskH.Reorder)
			auth.PATCH("/tasks/:id", taskH.Update)
			auth.POST("/tasks/:id/toggle", taskH.Toggle)
			auth.POST("/tasks/:id/abandon", taskH.Abandon)
			auth.POST("/tasks/:id/restore", taskH.Restore)
			auth.POST("/tasks/:id/trash", taskH.Trash)
			auth.DELETE("/tasks/:id", taskH.Delete)

			auth.GET("/lists", listH.List)
			auth.POST("/lists", listH.Create)
			auth.PATCH("/lists/:id", listH.Update)
			auth.DELETE("/lists/:id", listH.Delete)

			auth.GET("/mcp-token", mcpTokenH.GetStatus)
			auth.POST("/mcp-token", mcpTokenH.Generate)
			auth.DELETE("/mcp-token", mcpTokenH.Revoke)
		}
	}

	mcpGroup := r.Group("/mcp")
	mcpGroup.Use(middleware.Auth(jwtHelper))
	mcpGroup.Use(middleware.InjectUserIDForMCP())
	{
		mcpGroup.GET("/sse", gin.WrapH(mcpServer.SSEHandler()))
		mcpGroup.POST("/message", gin.WrapH(mcpServer.MessageHandler()))
	}

	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	return r
}
